# Generated by Django 3.2.5 on 2021-07-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0002_auto_20210717_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='q1',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='q2',
            field=models.CharField(max_length=3),
        ),
    ]
