# Generated by Django 3.2.5 on 2021-07-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0014_auto_20210718_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='nm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
