# Generated by Django 3.2.5 on 2021-07-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0016_auto_20210719_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizFriendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique', models.CharField(blank=True, max_length=10)),
                ('marks', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
