# Generated by Django 3.2.5 on 2021-07-28 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0021_auto_20210728_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizfriendmodel',
            name='unique',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='QuizApp.quizmodel'),
        ),
    ]
