# Generated by Django 3.2.5 on 2021-07-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0023_alter_quizmodel_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizfriendmodel',
            name='unique',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
