# Generated by Django 3.2.5 on 2021-09-18 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0024_alter_quizfriendmodel_unique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizmodel',
            old_name='nm',
            new_name='name',
        ),
    ]
