# Generated by Django 3.2.5 on 2021-11-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0025_rename_nm_quizmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='producting')),
                ('category', models.CharField(choices=[('Pow', 'Power Ranger'), ('Ben', 'Ben 10')], max_length=4)),
            ],
        ),
    ]
