# Generated by Django 3.2.5 on 2021-11-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0026_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='picture',
            new_name='picture_1',
        ),
        migrations.AddField(
            model_name='question',
            name='picture_2',
            field=models.ImageField(default=1, upload_to='producting'),
        ),
        migrations.AddField(
            model_name='question',
            name='picture_3',
            field=models.ImageField(default=1, upload_to='producting'),
        ),
    ]
