# Generated by Django 3.2.5 on 2021-11-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0027_auto_20211106_1017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizModel',
            new_name='QuizUserModel',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
    ]
