# Generated by Django 3.2.5 on 2021-11-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0028_auto_20211106_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizusermodel',
            old_name='q1',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='quizusermodel',
            old_name='q2',
            new_name='quest_id',
        ),
    ]
