# Generated by Django 3.2.5 on 2021-11-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0029_auto_20211106_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
    ]
