# Generated by Django 3.2.5 on 2021-11-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0031_auto_20211109_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizfriendmodel',
            name='name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='quizusermodel',
            name='category',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='quizusermodel',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quizusermodel',
            name='quest_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
