# Generated by Django 3.2.5 on 2021-11-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0032_auto_20211109_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizfriendmodel',
            name='category',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='quizfriendmodel',
            name='quest_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='quizfriendmodel',
            name='score',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
