# Generated by Django 3.2.5 on 2021-11-09 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0033_auto_20211109_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizfriendmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quizfriendmodel',
            name='quest_id',
        ),
    ]
