# Generated by Django 3.2.5 on 2021-11-11 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0035_auto_20211111_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizfriendmodel',
            name='user_belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApp.quizusermodel'),
        ),
    ]
