# Generated by Django 3.2.5 on 2021-11-11 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0038_auto_20211111_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizfriendmodel',
            name='user_belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApp.quizusermodel'),
        ),
    ]
