# Generated by Django 3.2.5 on 2021-11-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0039_alter_quizfriendmodel_user_belong_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizfriendmodel',
            name='score',
            field=models.PositiveIntegerField(max_length=10, null=True),
        ),
    ]
