# Generated by Django 3.2.5 on 2021-11-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0040_alter_quizfriendmodel_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizfriendmodel',
            name='score',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quizfriendmodel',
            name='user_belong_to',
            field=models.CharField(max_length=50),
        ),
    ]
